# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opiekun', '0003_auto_20160604_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dziecko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opiekun.Grupa')),
            ],
            options={
                'verbose_name_plural': 'dzieci',
            },
        ),
        migrations.CreateModel(
            name='Rodzic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dziecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodzic.Dziecko')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'rodzice',
            },
        ),
    ]
